baseURL: https://dhtzs.dev/
languageCode: en-us
title: "dhtzs.dev"
theme: PaperMod
paginate: 5

enableRobotsTXT: true
buildDrafts: true
buildFuture: false
buildExpired: false
pluralizeListTitles : false
sitemap:
  changefreq: "monthly"
  filename: "sitemap.xml"

googleAnalytics: "G-LVC4CS3028"

security:
  enableInlineShortcodes: true

minify:
  disableXML: true
#   minifyOutput: true
disableHugoGeneratorInject: true
disableKinds: ["taxonomy", "term"]

params:
  env: "production"
  title: "Dimitris Chatzis"
  description: "Explore my persona — A student, programmer, and bug bounty hunter on a digital journey."
  author: "Dimitris Chatzis"
  keywords: ["Dimitris Chatzis", "portfolio"]
  images: ["images/logo.png"]
  defaultTheme: auto
  DateFormat: "October 30, 2001"
  ShowReadingTime: true
  ShowShareButtons: true
  ShowCodeCopyButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  ShowAllPagesInArchive: true
  ShowToc: true
  UseHugoToc: true
  TocOpen: false
  disableAnchoredHeadings: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hideMeta: false
  hideSummary: false
  socialIcons:
    - name: "LinkedIn"
      url: "https://linkedin.com/in/dimitris-chatzis"
    - name: "X"
      url: "https://twitter.com/dhtzs"
    - name: "GitHub"
      url: "https://github.com/dhtzs"
    - name: "Discord"
      url: "https://discordapp.com/users/685173086022402060"
    - name: "HackerOne"
      url: "https://hackerone.com/dhtzs"
    - name: "Bugcrowd"
      url: "https://bugcrowd.com/dhtzs"
    - name: "Intigriti"
      url: "https://intigriti.com/profile/dhtzs"
    - name: "Email"
      url: "#"
  schema:
    sameAs:
      - "https://linkedin.com/in/dimitris-chatzis"
      - "https://twitter.com/dhtzs"
      - "https://github.com/dhtzs"
      - "https://discordapp.com/users/685173086022402060"
      - "https://hackerone.com/dhtzs"
      - "https://bugcrowd.com/dhtzs"
      - "https://intigriti.com/profile/dhtzs"
  assets:
    disableHLJS: true
    favicon: "favicon.ico"
    favicon16x16: "favicons/favicon-16x16.png"
    favicon32x32: "favicons/favicon-32x32.png"
    apple_touch_icon: "favicons/favicon-180x180.png"
    safari_pinned_tab: "favicons/favicon.svg"
    theme_color: "#1D1E20"
    msapplication_TileColor: "#1D1E20"
  editPost:
    URL: "https://github.com/dhtzs/dhtzs.github.io/edit/main/content"
    Text: "Suggest changes"
    appendFilePath: true

markup:
  highlight:
    codeFences: true
    guessSyntax: true
    lineNos: true
    style: monokai

menu:
  main:
  - name: "Home"
    url: "/"
    weight: 1
  - name: "About me"
    url: "/about-me"
    weight: 2
  - name: "Write-ups"
    url: "/write-ups"
    weight: 3

outputs:
  home:
    - HTML
    - RSS
    - JSON

languages:
  en:
    params:
      languageName: "English"
      weight: 1
      profileMode:
        enabled: true
        title: "Dimitris Chatzis"
        subtitle: "Student of [Digital Systems](https://ds.uth.gr/en) in [University of Thessaly](https://www.uth.gr/en), programmer and hacking enthusiast. Bug Bounty Hunter at HackerOne, Bugcrowd and Intigriti."
        imageUrl: "/images/profile"
        imageTitle: "Dimitris Chatzis"
