baseURL: https://dhtzs.dev/
languageCode: en-us
title: "dhtzs.dev"
theme: PaperMod
pagination:
  pagerSize: 5
timeout: 60

enableRobotsTXT: true
build:
  buildStats:
    enable: true
buildDrafts: true
buildFuture: false
buildExpired: false
pluralizeListTitles: false
pygmentsUseClasses: true
sitemap:
  changefreq: "monthly"
  filename: "sitemap.xml"

services:
  googleAnalytics:
    id: "G-LVC4CS3028"
privacy:
  googleAnalytics:
    respectDoNotTrack: true
    disable: true

security:
  enableInlineShortcodes: true

minify:
  disableXML: true
  minifyOutput: false
disableHugoGeneratorInject: true
disableKinds: ["taxonomy", "term", "RSS"]

params:
  env: "production"
  title: "Dimitris Chatzis"
  description: "Explore my persona — A student, programmer, and bug bounty hunter on a digital journey."
  footer:
    hideCopyright: false
  author: "Dimitris Chatzis"
  keywords: ["Dimitris Chatzis", "portfolio"]
  images: ["images/logo.png"]
  defaultTheme: auto
  DateFormat: "October 30, 2001"
  ShareButtons: ["x", "linkedin", "reddit", "telegram"]
  ShowShareButtons: true
  ShowReadingTime: true
  ShowCodeCopyButtons: true
  ShowPageNums: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: false
  ShowAllPagesInArchive: true
  ShowToc: true
  UseHugoToc: true
  TocOpen: false
  disableAnchoredHeadings: true
  disableThemeToggle: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hideMeta: false
  hideSummary: false
  socialIcons:
    - name: "LinkedIn"
      url: "https://linkedin.com/in/dimitris-chatzis"
    - name: "X"
      url: "https://twitter.com/dhtzs"
    - name: "GitHub"
      url: "https://github.com/dhtzs"
    - name: "HackerOne"
      url: "https://hackerone.com/dhtzs"
    - name: "Bugcrowd"
      url: "https://bugcrowd.com/dhtzs"
    - name: "Intigriti"
      url: "https://intigriti.com/profile/dhtzs"
    - name: "PGPKey"
      url: "/pgp-key.txt"
    - name: "Email"
      url: "#"
  schema:
    sameAs:
      - "https://linkedin.com/in/dimitris-chatzis"
      - "https://twitter.com/dhtzs"
      - "https://github.com/dhtzs"
      - "https://hackerone.com/dhtzs"
      - "https://bugcrowd.com/dhtzs"
      - "https://intigriti.com/profile/dhtzs"
  assets:
    disableFingerprinting: true
    favicon: "favicon.ico"
    favicon16x16: "favicons/favicon-16x16.png"
    favicon32x32: "favicons/favicon-32x32.png"
    apple_touch_icon: "favicons/favicon-180x180.png"
    safari_pinned_tab: "favicons/favicon.svg"
    theme_color: "#1D1E20"
    msapplication_TileColor: "#1D1E20"
  fuseOpts:
    isCaseSensitive: false
    includeScore: false
    includeMatches: false
    minMatchCharLength: 1
    shouldSort: true
    findAllMatches: false
    keys: ["title", "content"]
    location: 0
    threshold: 0.4
    distance: 100
    ignoreLocation: true
  editPost:
    URL: "https://github.com/dhtzs/dhtzs.dev/edit/main/content"
    Text: "Suggest changes"
    appendFilePath: true
  mainSections:
    - "write-ups"

markup:
  highlight:
    style: catppuccin-macchiato
    codeFences: true
    guessSyntax: true
    lineNos: true
    noClasses: false
    tabWidth: 4

menu:
  main:
    - name: "/home"
      url: "/"
      weight: 1
    - name: "/about-me"
      url: "/about-me/"
      weight: 2
    - name: "/write-ups"
      url: "/write-ups/"
      weight: 3

outputs:
  home:
    - HTML
    - JSON

languages:
  en:
    params:
      languageName: "English"
      weight: 1
      profileMode:
        enabled: true
        title: "Dimitris Chatzis"
        subtitle: "Student of [Digital Systems](https://ds.uth.gr/en) in [University of Thessaly](https://www.uth.gr/en), programmer and hacking enthusiast. Bug Bounty Hunter at HackerOne, Bugcrowd and Intigriti."
        imageUrl: "/images/profile"
        imageTitle: "Dimitris Chatzis"
